const PATHROUTES = {
  HOME: "/",
  LOGIN: "/signin",
  REGISTER: "/signup",
  USER_DASHBOARD: "/userDashboard",
  ADMIN_DASHBOARD: "/adminDashboard",
  VET_DASHBOARD: "/vetDashboard",
  PET: "/pet",
  NEW_PET: "/pet/newpet",
  CART: "/cart",
  SEARCH: "/search",
  FAQ: "/Q&A",
  ABOUTUS: "/aboutus",
  TERMS: "/terms",
  PRIVACY: "/privacypolicy",
  APPOINTMENT: "/appointment",
  NEWAPPOINTMEN: "/appointment/newAppointment",
  WHATSAPP: "https://wa.me/",
  CALIFICAR: "https://forms.gle/quKt5d1b7saptcyn9",
  BILL: "/adminDashboard/",
  NEW_VET: "/adminDashboard/newVet",
  NEW_CUPON: "/adminDashboard/newCupon",
};

export default PATHROUTES;
